# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\attandancegui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Attendance_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(980, 530)
        Dialog.setMaximumSize(QtCore.QSize(1024, 768))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.imgLabel = QtWidgets.QLabel(Dialog)
        self.imgLabel.setGeometry(QtCore.QRect(10, 40, 640, 480))
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(659, 10, 301, 511))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(150, 10, 141, 101))
        self.groupBox.setObjectName("groupBox")
        self.AccuracyButton = QtWidgets.QPushButton(self.groupBox)
        self.AccuracyButton.setGeometry(QtCore.QRect(11, 60, 121, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/accuracy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccuracyButton.setIcon(icon)
        self.AccuracyButton.setObjectName("AccuracyButton")
        self.TrainButton = QtWidgets.QPushButton(self.groupBox)
        self.TrainButton.setGeometry(QtCore.QRect(11, 21, 121, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/train.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TrainButton.setIcon(icon1)
        self.TrainButton.setObjectName("TrainButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 120, 141, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.BrowseButton = QtWidgets.QPushButton(self.groupBox_2)
        self.BrowseButton.setGeometry(QtCore.QRect(10, 20, 121, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/image files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BrowseButton.setIcon(icon2)
        self.BrowseButton.setObjectName("BrowseButton")
        self.UpdateImageAttandanceButton = QtWidgets.QPushButton(self.groupBox_2)
        self.UpdateImageAttandanceButton.setGeometry(QtCore.QRect(10, 60, 121, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/attendance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UpdateImageAttandanceButton.setIcon(icon3)
        self.UpdateImageAttandanceButton.setObjectName("UpdateImageAttandanceButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 281, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.OpenCameraButton = QtWidgets.QPushButton(self.groupBox_3)
        self.OpenCameraButton.setGeometry(QtCore.QRect(10, 15, 121, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/photo-camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.OpenCameraButton.setIcon(icon4)
        self.OpenCameraButton.setCheckable(False)
        self.OpenCameraButton.setObjectName("OpenCameraButton")
        self.TakePhotoButton = QtWidgets.QPushButton(self.groupBox_3)
        self.TakePhotoButton.setGeometry(QtCore.QRect(150, 15, 121, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TakePhotoButton.setIcon(icon5)
        self.TakePhotoButton.setObjectName("TakePhotoButton")
        self.LiveManualAttandanceButton = QtWidgets.QPushButton(self.groupBox_3)
        self.LiveManualAttandanceButton.setGeometry(QtCore.QRect(150, 50, 121, 31))
        self.LiveManualAttandanceButton.setIcon(icon3)
        self.LiveManualAttandanceButton.setObjectName("LiveManualAttandanceButton")
        self.StopCameraButton = QtWidgets.QPushButton(self.groupBox_3)
        self.StopCameraButton.setGeometry(QtCore.QRect(10, 50, 121, 31))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/close camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopCameraButton.setIcon(icon6)
        self.StopCameraButton.setObjectName("StopCameraButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 330, 281, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.ShowRecordButton = QtWidgets.QPushButton(self.groupBox_4)
        self.ShowRecordButton.setGeometry(QtCore.QRect(11, 15, 111, 31))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ShowRecordButton.setIcon(icon7)
        self.ShowRecordButton.setObjectName("ShowRecordButton")
        self.GenerateCSVButton = QtWidgets.QPushButton(self.groupBox_4)
        self.GenerateCSVButton.setGeometry(QtCore.QRect(170, 15, 101, 31))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/csv file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GenerateCSVButton.setIcon(icon8)
        self.GenerateCSVButton.setIconSize(QtCore.QSize(26, 16))
        self.GenerateCSVButton.setObjectName("GenerateCSVButton")
        self.studentNameComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.studentNameComboBox.setGeometry(QtCore.QRect(10, 60, 121, 22))
        self.studentNameComboBox.setObjectName("studentNameComboBox")
        self.monthComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.monthComboBox.setGeometry(QtCore.QRect(10, 98, 121, 22))
        self.monthComboBox.setObjectName("monthComboBox")
        self.percentageAttendanceButton = QtWidgets.QPushButton(self.groupBox_4)
        self.percentageAttendanceButton.setGeometry(QtCore.QRect(150, 59, 121, 31))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/percentage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.percentageAttendanceButton.setIcon(icon9)
        self.percentageAttendanceButton.setIconSize(QtCore.QSize(20, 20))
        self.percentageAttendanceButton.setObjectName("percentageAttendanceButton")
        self.percentage_attendance_label = QtWidgets.QLabel(self.groupBox_4)
        self.percentage_attendance_label.setGeometry(QtCore.QRect(150, 100, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.percentage_attendance_label.setFont(font)
        self.percentage_attendance_label.setFrameShape(QtWidgets.QFrame.Box)
        self.percentage_attendance_label.setText("")
        self.percentage_attendance_label.setObjectName("percentage_attendance_label")
        self.refreshComboBoxButton = QtWidgets.QPushButton(self.groupBox_4)
        self.refreshComboBoxButton.setGeometry(QtCore.QRect(126, 15, 41, 31))
        self.refreshComboBoxButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshComboBoxButton.setIcon(icon10)
        self.refreshComboBoxButton.setIconSize(QtCore.QSize(25, 25))
        self.refreshComboBoxButton.setObjectName("refreshComboBoxButton")
        self.ExitButton = QtWidgets.QPushButton(self.groupBox_5)
        self.ExitButton.setGeometry(QtCore.QRect(20, 472, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ExitButton.setFont(font)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitButton.setIcon(icon11)
        self.ExitButton.setObjectName("ExitButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 120, 131, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_6)
        self.timeEdit.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.timeEdit.setTime(QtCore.QTime(10, 0, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.StartAutoAttandanceButton = QtWidgets.QPushButton(self.groupBox_6)
        self.StartAutoAttandanceButton.setGeometry(QtCore.QRect(10, 59, 111, 31))
        self.StartAutoAttandanceButton.setObjectName("StartAutoAttandanceButton")
        self.addPersonButton = QtWidgets.QPushButton(self.groupBox_5)
        self.addPersonButton.setGeometry(QtCore.QRect(26, 30, 101, 71))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/persons.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPersonButton.setIcon(icon12)
        self.addPersonButton.setIconSize(QtCore.QSize(25, 25))
        self.addPersonButton.setObjectName("addPersonButton")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 131, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_7.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.ExitButton.raise_()
        self.groupBox_6.raise_()
        self.addPersonButton.raise_()
        self.Accuracy_label = QtWidgets.QLabel(Dialog)
        self.Accuracy_label.setGeometry(QtCore.QRect(590, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Accuracy_label.setFont(font)
        self.Accuracy_label.setFrameShape(QtWidgets.QFrame.Box)
        self.Accuracy_label.setText("")
        self.Accuracy_label.setObjectName("Accuracy_label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(430, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Attendance System using Machine Learning"))
        self.label.setText(_translate("Dialog", "Live Camera Feed or static Image"))
        self.groupBox.setTitle(_translate("Dialog", "Training Process"))
        self.AccuracyButton.setToolTip(_translate("Dialog", "Calculate the accuracy of Dataset"))
        self.AccuracyButton.setText(_translate("Dialog", "Accuracy"))
        self.TrainButton.setToolTip(_translate("Dialog", "Train the LBPFaceRecogniser"))
        self.TrainButton.setText(_translate("Dialog", "Training"))
        self.groupBox_2.setTitle(_translate("Dialog", "Image Recognition"))
        self.BrowseButton.setToolTip(_translate("Dialog", "Browse Local Image for Recognition"))
        self.BrowseButton.setText(_translate("Dialog", "Browse Image"))
        self.UpdateImageAttandanceButton.setToolTip(_translate("Dialog", "Mark Attendance in MySQL Database"))
        self.UpdateImageAttandanceButton.setText(_translate("Dialog", "Attandance"))
        self.groupBox_3.setTitle(_translate("Dialog", "Manual Recognition"))
        self.OpenCameraButton.setText(_translate("Dialog", "Open Camera"))
        self.TakePhotoButton.setText(_translate("Dialog", "Take Photo"))
        self.LiveManualAttandanceButton.setText(_translate("Dialog", "Attandance"))
        self.StopCameraButton.setText(_translate("Dialog", "Stop Camera"))
        self.groupBox_4.setTitle(_translate("Dialog", "Attendance Record"))
        self.ShowRecordButton.setToolTip(_translate("Dialog", "Show Complete Year Data"))
        self.ShowRecordButton.setText(_translate("Dialog", "Show All Records"))
        self.GenerateCSVButton.setToolTip(_translate("Dialog", "Make CSV file for further Inquiries"))
        self.GenerateCSVButton.setText(_translate("Dialog", "Make CSV File"))
        self.studentNameComboBox.setToolTip(_translate("Dialog", "Select Students"))
        self.monthComboBox.setToolTip(_translate("Dialog", "Select Month"))
        self.percentageAttendanceButton.setToolTip(_translate("Dialog", "Get Percentile Attendance of Selected Student"))
        self.percentageAttendanceButton.setText(_translate("Dialog", "Attendance"))
        self.refreshComboBoxButton.setToolTip(_translate("Dialog", "Refresh Combo Boxes"))
        self.ExitButton.setToolTip(_translate("Dialog", "EXIT Program"))
        self.ExitButton.setText(_translate("Dialog", "Exit"))
        self.groupBox_6.setTitle(_translate("Dialog", "Auto Attandance"))
        self.StartAutoAttandanceButton.setToolTip(_translate("Dialog", "Start Automatic Attendance"))
        self.StartAutoAttandanceButton.setText(_translate("Dialog", "Start Auto"))
        self.addPersonButton.setToolTip(_translate("Dialog", "Add New person to Dataset"))
        self.addPersonButton.setText(_translate("Dialog", "Add Person"))
        self.groupBox_7.setTitle(_translate("Dialog", "Dataset Creation"))
        self.label_2.setText(_translate("Dialog", "Accuracy (%) :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Attendance_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

